KUBECONFIG_1: /Users/USER/.kube/cafev1.yaml
KUBECONFIG_2: /Users/USER/.kube/cafev2.yaml
KUBE_WORKERS_1:
  - 172.20.0.149
  - 172.20.0.124
  - 172.20.0.8
KUBE_WORKERS_2:
  - 10.0.10.182
  - 10.0.10.195
  - 10.0.10.110
POD_CIDR_1: 10.232.64.0/18
SERVICE_CIDR_1: 10.96.0.0/12
POD_CIDR_2: 10.234.64.0/18
SERVICE_CIDR_2: 10.112.0.0/12
