- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install blackbox exporter
  package:
    name: prometheus-blackbox-exporter
    state: present
  become: yes
  retries: 3
  delay: 10

- name: Create blackbox exporter configuration directory
  file:
    path: /etc/blackbox_exporter
    state: directory
    mode: "0755"
  become: yes

- name: Configure blackbox exporter
  template:
    src: blackbox.yml.j2
    dest: /etc/blackbox_exporter/blackbox.yml
    mode: "0644"
  notify: restart blackbox exporter
  become: yes

- name: Set capabilities for blackbox exporter to allow ICMP
  command: setcap cap_net_raw+ep /usr/bin/prometheus-blackbox-exporter
  become: yes

- name: Configure existing blackbox exporter service
  systemd:
    name: prometheus-blackbox-exporter
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes

- name: Create prometheus targets configuration
  template:
    src: prometheus-targets.yml.j2
    dest: /etc/blackbox_exporter/prometheus-targets.yml
    mode: "0644"
  become: yes

- name: Enable and start blackbox exporter
  systemd:
    name: prometheus-blackbox-exporter
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
